name: RetOCTNet
channels:
  - conda-forge
  - defaults
dependencies:

  - numpy-base=1.23.5
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - pip
  - pyparsing=3.0.9
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.9.0
  - python-dateutil
  - pywavelets
  - pyyaml
  - yaml

  - pip:
  
    - h5py==3.7.0
    - joblib==1.2.0
    - keras==2.10.0
    - keras-preprocessing==1.1.2
    - matplotlib==3.6.3
    - numpy==1.23.2
    - opencv-python
    - openpyxl==3.1.1
    - opt-einsum==3.3.0
    - pandas==1.5.3
    - pillow==9.4.0
    - pluggy==1.0.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydicom==2.3.1
    - pyerfa==2.0.0.3
    - pytest==7.3.1
    - pytz==2022.7.1
    - reproject==0.10.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - seaborn==0.12.2
    - sentry-sdk==1.14.0
    - setproctitle==1.3.2
    - shutilwhich==1.1.0
    - simpleitk==2.2.1
    - smmap==5.0.0
    - statsmodels==0.13.5
    - tempdir==0.7.1
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==2.10.0
    - tensorflow-estimator==2.10.0
    - tensorflow-io-gcs-filesystem==0.26.0
    - termcolor==1.1.0
    - threadpoolctl==3.1.0
    - tifffile==2023.2.27
    - tomli==2.0.1
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - werkzeug==3.0.3
    - wrapt==1.14.1
    - zipp==3.8.1
